#!/usr/bin/env bash
# script that kills the process 7-highlander

# Use pkill to stop the '7-highlander' process
pkill -f "7-highlander"

if pgrep -f "7-highlander" > /dev/null
then
    pkill -9 -f "7-highlander"
fi
